name: ekaadh_mobile
description: Ekaadh event ticketing mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  pdf: ^3.12.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  uuid: ^4.6.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  share_plus: ^10.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ekaadh_logo.png
    - assets/images/ekaadh_logo_white.png
    - assets/images/ekaadh_icon.png
